Add support for manually running workflows on PRs from forks (#109)
* Add support for manually running workflows on PRs from forks

* Fix ci.yml

* Fix ci.yml #2

* Support manual workflow runs

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,11 +1,18 @@
-name: Build
+# Note: We use the insecure pull_request_target to allow running workflows from forks.
+# However, we've added checks (see below) for safety.
+# In short, the 'safe to test' label must exist AND the workflow must be run by someone with write access.
+# See more details here:
+#   - https://securitylab.github.com/resources/github-actions-preventing-pwn-requests/
+#   - https://michaelheap.com/access-secrets-from-forks/
+name: Build and Test
 on:
   push:
     branches: [ main ]
-  pull_request:
+  pull_request_target:
     branches: [ '*' ]
   schedule:
   - cron: "0 5 * * WED"
+  workflow_dispatch:
 jobs:
   run:
     runs-on: ubuntu-latest
@@ -17,10 +24,47 @@ jobs:
           - python-version: "3.9"
             polars-version: "0.20.27"
     steps:
+      # Important checks to ensure that the user has the required permissions. See note above.
+      # Step 1: If user has current permissions we're good!
+      - name: Get User Permission
+        id: checkAccess
+        uses: actions-cool/check-user-permission@v2
+        with:
+          require: write
+          username: ${{ github.actor }}
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      # Otherwise, get triggering user's permissions
+      - name: Get Triggering User Permission
+        if: steps.checkAccess.outputs.require-result == 'false'
+        id: checkTriggeringAccess
+        uses: actions-cool/check-user-permission@v2
+        with:
+          require: write
+          username: ${{ github.triggering_actor }}
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      # If neither has permissions throw error
+      - name: Check User Permission
+        if: steps.checkAccess.outputs.require-result == 'false' && steps.checkTriggeringAccess.outputs.require-result == 'false'
+        shell: bash
+        run: |
+          echo "${{ github.triggering_actor }} does not have permissions on this repo."
+          echo "Current permission level is ${{ steps.checkAccess.outputs.user-permission }}"
+          echo "Job originally triggered by ${{ github.actor }}"
+          exit 1
+      # If no 'safe to test' label also throw error
+      - name: Check Label
+        if: steps.checkAccess.outputs.require-result == 'false' && !contains(github.event.pull_request.labels.*.name, 'safe to test')
+        shell: bash
+        run: |
+          echo "The 'safe to test' label is required to run this workflow since ${{ github.actor }} does not have permissions on this repo."
+          exit 1
       - name: Checkout
         uses: actions/checkout@v4
         with:
           fetch-depth: 0
+          ref: ${{ github.event.pull_request.head.sha }} # This is dangerous without the first access check. See note above.
       - name: Set up Python ${{ matrix.python-version }}
         uses: actions/setup-python@v5
         with:
